version: '3.8'

services:

#  beer-api:
#    image: beer-api:latest
#    build:
#      context: .
#      dockerfile: beer-api/Dockerfile
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://beer-db:5431/beer_db
#      SPRING_DATASOURCE_USERNAME: beer_user
#      SPRING_DATASOURCE_PASSWORD: beer_password
#    depends_on:
#      - beer-db

  beer-db:
    image: postgres:17
    container_name: beer-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: beer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwrd1
    volumes:
      - beer-db-data:/var/lib/postgresql/data

volumes:
  beer-db-data: